import {
    Shirt,
    GraduationCap,
    ShoppingCart,
    Heart,
    Gamepad2,
    Stethoscope,
    Bed,
    Car,
    Cake,
    Users,
    Wallet,
    HelpCircle,
    Home,
    Plug,
    Wifi,
    Tv,
    ShieldCheck,
    Dumbbell,
    BookUser,
    HeartHandshake,
    CreditCard,
    Ticket,
    Smartphone,
} from "lucide-react"

export const iconMap: Record<string, any> = {
    "Miete": Home,
    "Strom": Plug,
    "Internet": Wifi,
    "Streamingdienste": Tv,
    "Versicherungen": ShieldCheck,
    "Fitnessstudio": Dumbbell,
    "Abonnements": BookUser,
    "Ratenzahlung": CreditCard,
    "Mitgliedschaften": HeartHandshake,
    "ÖPNV": Ticket,
    "Mobilfunkvertrag": Smartphone,

    "Kleidung": Shirt,
    "Schule": GraduationCap,
    "Lebensmittel": ShoppingCart,
    "Hobbys": Heart,
    "Spielzeug": Gamepad2,
    "Gesundheit": Stethoscope,
    "Kinderzimmer": Bed,
    "Transport": Car,
    "Geburtstage": Cake,
    "Betreuung": Users,
    "Finanzen": Wallet,
    "Sonstiges": HelpCircle,
}
