import {
    Bed,
    BookUser,
    Cake,
    Car,
    CreditCard,
    Dumbbell,
    Gamepad2,
    GraduationCap,
    Heart,
    HeartHandshake,
    HelpCircle,
    Home,
    Plug,
    ShieldCheck,
    Shirt,
    ShoppingCart,
    Smartphone,
    Stethoscope,
    Sun,
    Tv,
    Users,
    Wallet,
    Wifi,
} from 'lucide-react'

export const availableIcons = [
    { icon: Home, name: 'Miete', defaultLabel: 'Miete' },
    { icon: Sun, name: 'Urlaub', defaultLabel: 'Urlaub' },
    { icon: Plug, name: 'Strom', defaultLabel: 'Strom' },
    { icon: Wifi, name: 'Internet', defaultLabel: 'Internet' },
    { icon: Tv, name: 'Streaming', defaultLabel: 'Streamingdienste' },
    { icon: ShieldCheck, name: 'Versicherungen', defaultLabel: 'Versicherungen' },
    { icon: Dumbbell, name: 'Sport', defaultLabel: 'Sport' },
    { icon: BookUser, name: 'Abos', defaultLabel: 'Abonnements' },
    { icon: CreditCard, name: 'Ratenzahlung', defaultLabel: 'Ratenzahlung' },
    { icon: HeartHandshake, name: 'Mitgliedschaften', defaultLabel: 'Mitgliedschaften' },

    { icon: Smartphone, name: 'Mobilfunk', defaultLabel: 'Mobilfunkvertrag' }, // ← NEU

    { icon: Shirt, name: 'Kleidung', defaultLabel: 'Kleidung' },
    { icon: GraduationCap, name: 'Schule', defaultLabel: 'Schule' },
    { icon: ShoppingCart, name: 'Lebensmittel', defaultLabel: 'Lebensmittel' },
    { icon: Heart, name: 'Hobbys', defaultLabel: 'Hobbys' },
    { icon: Gamepad2, name: 'Spielzeug', defaultLabel: 'Spielzeug' },
    { icon: Stethoscope, name: 'Gesundheit', defaultLabel: 'Gesundheit' },
    { icon: Bed, name: 'Möbiliar', defaultLabel: 'Möbiliar' },
    { icon: Car, name: 'Transport', defaultLabel: 'Transport' },
    { icon: Cake, name: 'Geburtstage', defaultLabel: 'Geburtstage' },
    { icon: Users, name: 'Betreuung', defaultLabel: 'Betreuung' },
    { icon: Wallet, name: 'Finanzen', defaultLabel: 'Finanzen' },
    { icon: HelpCircle, name: 'Sonstiges', defaultLabel: 'Sonstiges' },
]
