import {
    Bed,
    BookUser,
    Cake,
    Car,
    CreditCard,
    Dumbbell,
    Gamepad2,
    GraduationCap,
    Heart,
    HeartHandshake,
    HelpCircle,
    Home,
    Plug,
    ShieldCheck,
    Shirt,
    ShoppingCart,
    Smartphone,
    Stethoscope,
    Sun,
    Ticket,
    Tv,
    Users,
    Wallet,
    Wifi,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
export const iconMap: Record<string, LucideIcon> = {
    Urlaub: Sun,
    Miete: Home,
    Strom: Plug,
    Internet: Wifi,
    Streamingdienste: Tv,
    Versicherungen: ShieldCheck,
    Fitnessstudio: Dumbbell,
    Abonnements: BookUser,
    Ratenzahlung: CreditCard,
    Mitgliedschaften: HeartHandshake,
    ÖPNV: Ticket,
    Mobilfunkvertrag: Smartphone,

    Kleidung: Shirt,
    Schule: GraduationCap,
    Lebensmittel: ShoppingCart,
    Hobbys: Heart,
    Spielzeug: Gamepad2,
    Gesundheit: Stethoscope,
    Kinderzimmer: Bed,
    Transport: Car,
    Geburtstage: Cake,
    Betreuung: Users,
    Finanzen: Wallet,
    Sonstiges: HelpCircle,
}
